# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d-TJ5wXF-mel86jUQGse7B6ZFvhwdBF1
"""

import polars as pl
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

df = pd.read_csv("ttc_delays.csv")
print(df.head())

df.info()

df.describe()

sb.set_palette("Blues")
plt.figure(figsize=(8, 6))

sb.pairplot(df)

plt.show()

"""**Diagonal Lines**

- Min Delay vs. Min Gap

- Max Temp vs. Min Temp

- Max Temp vs. Mean Temp

- Min Temp vs. Mean Temp


Use mean temp? exclude min and max temp


"""

# Heatmap

numeric = df.select_dtypes(include=[float, int])

plt.figure(figsize=(15, 10))

sb.heatmap(numeric.corr(), annot=True, fmt='.2f', cmap='crest', linewidths=2)

plt.show

"""date
time
vehicle

Min Delay vs. Day
"""

df['Day'] = df['Day'].astype('category')

sb.boxplot(x='Day', y='Min Delay', data=df)

"""Min Gap vs. Day"""

sb.boxplot(x='Day', y='Min Gap', data=df)

"""Min Delay vs. Time

"""

df['Time'] = pd.to_timedelta(df['Time'])

sb.boxplot(x='Time', y='Min Delay', data=df)

plt.show()

"""Min Gap vs. Time"""

sb.boxplot(x='Time', y='Min Gap', data=df)

plt.show()

"""Min Delay vs. Vehicle"""

sb.boxplot(x='Vehicle', y='Min Delay', data=df)

plt.show()

df = pd.read_csv('ttc_delays.csv')
df.drop(columns=['Min Temp (°C)', 'Max Temp (°C)'])

df['Min Delay/Min Gap'] = df['Min Delay'] / df['Min Gap']

df['Min Delay/Min Gap'] = df['Min Delay/Min Gap'].replace([float('inf'), -float('inf')], 0)


df['Min Delay/Min Gap'] = df.apply(
    lambda row: row['Min Delay'] / row['Min Gap'] if row['Min Gap'] != 0 else 0, axis=1
)

df.to_csv('ttc_delays_ratio.csv', index=False)

print(df)